-- | **The Conspicillum reference, generated.** Every parameter, rule, chord and
-- | preset, written out as Markdown from the typed catalogue, so the reference
-- | is the code rather than a description of it.
-- |
-- | The committed `docs/CONSPICILLUM-REFERENCE.md` is this string, and the
-- | conformance suite prints it on node and on the BEAM and compares both with
-- | the file. So the document cannot drift from the instrument: change a range,
-- | a label or a preset, and the suite fails until the reference is
-- | regenerated (`node tools/conspicillum-reference.mjs`).
module Reef.Conspicillum.Reference
  ( reference
  ) where

import Prelude

import Data.Array (filter, length, null)
import Data.Either (Either(..))
import Data.Foldable (intercalate)
import Data.Maybe (fromMaybe, isNothing)
import Data.String as String
import Reef.Conspicillum.Harmonic (namedChords)
import Reef.Conspicillum.Notation (opNames)
import Reef.Conspicillum.Notation as Notation
import Reef.Conspicillum.Parameter (Section(..), Taper(..), allParameters, describe, format, identifier, notationTerm, opParameter, sectionName)
import Reef.Conspicillum.Cloud (Op(..))
import Reef.Conspicillum.Preset (Bank(..), Preset, bankName)
import Reef.Conspicillum.Presets (presets)

reference :: String
reference = intercalate "\n" (introduction <> parameters <> rules <> chords <> presetList) <> "\n"

introduction :: Array String
introduction =
  [ "# Conspicillum reference"
  , ""
  , "Generated from `Reef.Conspicillum.Reference`: the parameter catalogue, the rule vocabulary,"
  , "the chord table and the presets, as the code has them. Do not edit this file; change the"
  , "code and run `node tools/conspicillum-reference.mjs`. The conformance suite compares this"
  , "file with what node and the BEAM both print, so it cannot drift from the instrument."
  , ""
  , "A scene is written as one line, `#`-separated, the way Tidal writes a pattern:"
  , ""
  , "```"
  , "s \"fd-beat-bar\" # walk 0.2 0.1 0.1 # grid 8 # swing 0.62 # fix snare 0.5 (pshift 1.5)"
  , "```"
  , ""
  , "Anything a line does not say is Sector's default: sixteen grains a bar, following the tape."
  , "The **term** column below is how a line sets each parameter."
  , ""
  , "## Contents"
  , ""
  , "- [Parameters](#parameters)"
  , "- [Rules](#rules)"
  , "- [Chords](#chords)"
  , "- [Presets](#presets)"
  , ""
  ]

-- ── parameters ───────────────────────────────────────────────────────────────

parameters :: Array String
parameters =
  [ "## Parameters"
  , ""
  , "Every number a player can turn. **Neutral** is where a scene that says nothing about it"
  , "stands. **Needs** is what has to be engaged for it to be heard at all: an effect's depth"
  , "does nothing while its rate is off. Ranges marked *log* turn exponentially, so each step"
  , "of the knob is the same ratio."
  , ""
  ]
    <> (sections >>= section)
  where
  sections = [ Grain, ReadHead, Walk, Swing, Voice, Sends, GrainEffects, CloudEffects ]
  section s =
    let members = filter (\p -> (describe p).section == s) allParameters
    in
      [ "### " <> capitalise (sectionName s)
      , ""
      , "| parameter | term | range | neutral | needs | what it does |"
      , "|---|---|---|---|---|---|"
      ]
        <> map row members
        <> [ "" ]
  row p =
    let d = describe p
    in
      "| **" <> d.label <> "**<br>`" <> identifier p <> "`"
        <> " | `" <> notationTerm p <> "`"
        <> " | " <> format p d.low <> " – " <> format p d.high <> (if d.taper == Exponential then " *log*" else "")
        <> " | " <> format p d.neutral
        <> " | " <> needs p
        <> " | " <> d.about
        <> " |"
  needs p =
    let by = filter (_ /= p) (describe p).engagedBy
    in if null by then "" else intercalate " or " (map (_.label <<< describe) by)

-- ── rules ────────────────────────────────────────────────────────────────────

rules :: Array String
rules =
  [ "## Rules"
  , ""
  , "A rule picks grains and does one thing to them. Rules are what no hardware granulator can"
  , "express, because there a grain has no identity to count."
  , ""
  , "| which grains | written | |"
  , "|---|---|---|"
  , "| every *n*-th, from the *k*-th | `every 3 0 (speed -1)` | counts across bars, so every third grain stays every third |"
  , "| a chance of each | `sometimesBy 0.2 (ratchet 3)` | seeded: the same scene makes the same choices |"
  , "| all of them | `always (send 1)` | |"
  , "| the ones that read like a hit | `fix snare 0.5 (pshift 1.5)` | kick, snare or hat, above a score threshold |"
  , ""
  , "The amount can be one number, `\"a b c\"` for one value per firing, or `\"<a b c>\"` for one"
  , "value per bar, as in Tidal: `fix kick 0.5 (rsnpitch \"<36 36 39 31>\")` is a bassline played"
  , "by the kick drum."
  , ""
  , "| op | acts on | how |"
  , "|---|---|---|"
  ]
    <> map opRow opNames
    <> [ "" ]
  where
  opRow name =
    "| `" <> name <> "` | " <> actsOn name <> " | " <> how name <> " |"
  actsOn name = case name of
    "shift" -> "where the grain reads"
    "ratchet" -> "how many times it sounds"
    "send" -> "where it goes"
    _ -> fromMaybe "" (map (\p -> (describe p).label) (parameterOf name))
  how name = case name of
    "speed" -> "multiplies"
    "gain" -> "multiplies"
    "length" -> "multiplies the grain's length"
    "shift" -> "moves the read head by a fraction of the source, wrapping; on a followed tape, a jump"
    "ratchet" -> "one grain becomes *n* inside its own slot: the stutter, the roll"
    "send" -> "a copy to send bus 1 (A) or 2 (B), at the bus's level"
    _ -> "sets"
  parameterOf name = case Notation.parse ("s \"x\" # always (" <> name <> " 1)") of
    Right l -> case l.spec.rules of
      [ r ] -> opParameter r.op
      _ -> opParameter (OpSend 0.0)
    Left _ -> opParameter (OpSend 0.0)

-- ── chords ───────────────────────────────────────────────────────────────────

chords :: Array String
chords =
  [ "## Chords"
  , ""
  , "The chords a line can name, in `chords \"<…>\"`. A progression plays one a cycle; the cloud"
  , "keeps to samples that fit the chord (`fit` minimum, strength) and the resonators can follow"
  , "it (`tune root`, `tune bass`, `tune tones`). Named for what the chord-hit corpora contain."
  , ""
  , "| chord | pitch classes | root | bass |"
  , "|---|---|---|---|"
  ]
    <> map row namedChords
    <> [ "" ]
  where
  row c = "| `" <> c.name <> "` | " <> intercalate " " (map pitchName c.target.pcs)
    <> " | " <> pitchName c.target.root <> " | " <> pitchName c.target.bass <> " |"

pitchName :: Int -> String
pitchName pc = case ((pc `mod` 12) + 12) `mod` 12 of
  0 -> "C"
  1 -> "C#"
  2 -> "D"
  3 -> "D#"
  4 -> "E"
  5 -> "F"
  6 -> "F#"
  7 -> "G"
  8 -> "G#"
  9 -> "A"
  10 -> "A#"
  _ -> "B"

-- ── presets ──────────────────────────────────────────────────────────────────

presetList :: Array String
presetList = case presets of
  Left problem -> [ "## Presets", "", "**A preset does not resolve:** " <> problem ]
  Right ps ->
    [ "## Presets"
    , ""
    , show (length ps) <> " presets in " <> show (length banks) <> " banks. Each is its line, and the knobs"
        <> " it puts on the panel; a query, where it has one, is noted."
    , ""
    ]
      <> (banks >>= bank ps)
  where
  banks = [ Early, Found, Polychords, Sector, Fix, Dub, Swung, Harmony, Envelopes, Effects, Resonators, Progressions ]
  bank ps b =
    let members = filter (\p -> p.bank == b) ps
    in
      if null members then []
      else [ "### " <> bankName b, "" ] <> (members >>= preset)
  preset :: Preset -> Array String
  preset p =
    [ "**" <> p.name <> "**" <> (if p.about == "" then "" else " — " <> p.about)
    , ""
    , "```"
    , Notation.print p.line
    , "```"
    , ""
    , "Knobs: " <> intercalate ", " (map (\k -> k.label <> " (" <> (describe k.parameter).label <> ")") p.knobs)
        <> (if null p.query.clauses && isNothing p.query.weighting then "" else ". Has a query.")
    , ""
    ]

capitalise :: String -> String
capitalise s = String.toUpper (String.take 1 s) <> String.drop 1 s
